# Generated by Django 3.2.8 on 2021-10-28 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('Advisor_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60)),
                ('Pic_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('Booking_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Time', models.CharField(max_length=60)),
                ('Advisor_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Advisor_API.advisor')),
                ('User_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Advisor_API.user')),
            ],
        ),
    ]
